export enum TicketsActionTypes {
    GET_ALL_TICKETS = "GET_ALL_TICKETS",
    GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS",
    GET_TICKETS_ERROR = "GET_TICKETS_ERROR",
    SET_TICKETS_LIMIT = "SET_TICKETS_LIMIT",
    SORT_TICKETS_BY_PRICE = "SORT_TICKETS_BY_PRICE",
    SORT_TICKETS_BY_DURATION = "SORT_TICKETS_BY_DURATION"
}